// monitor-ui.js
require("dotenv").config();
const fs = require("fs");
const path = require("path");
const { spawn } = require("child_process");
const readline = require("readline");

// simple prompt helper
function ask(question, defaultValue) {
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });

  const q =
    defaultValue !== undefined && defaultValue !== null
      ? `${question} (${defaultValue}): `
      : `${question}: `;

  return new Promise((resolve) => {
    rl.question(q, (answer) => {
      rl.close();
      if (!answer && defaultValue !== undefined) resolve(String(defaultValue));
      else resolve(answer.trim());
    });
  });
}

async function main() {
  console.log("=== Target Monitor Setup ===\n");

  // ONLY THING THEY NEED:
  const tcin = await ask("Enter TCIN", process.env.TCIN || "95040142");

  // OPTIONAL:
  const webhook = await ask(
    "Discord webhook URL (optional, press Enter to skip)",
    ""
  );

  // All other fields use SAFE defaults (shipping detection)
  const envContent = [
    "# === generated by monitor-ui.js ===",
    `TCIN=${tcin}`,
    `QTY=1`,
    "",
    "# Default location (safe for ALL users)",
    "STORE_ID=2342",
    "ZIP=78717",
    "STATE=TX",
    "LATITUDE=30.491921540848487",
    "LONGITUDE=-97.77130849066667",
    "",
    "# Polling",
    "POLL_MS=1000",
    "REFIRE_COOLDOWN_MS=30000",
    "SUCCESS_COOLDOWN_MS=300000",
    "",
    "LOG_DIR=./logs",
    webhook ? `DISCORD_WEBHOOK=${webhook}` : `DISCORD_WEBHOOK=`,
    "",
    "# (no cookies, no ATC, manual-only monitor)",
    "",
  ].join("\n");

  const envPath = path.join(__dirname, ".env");
  fs.writeFileSync(envPath, envContent, "utf8");

  console.log("\n✅ .env written.");
  console.log(`   TCIN    = ${tcin}`);
  console.log(
    `   Webhook = ${
      webhook && webhook.trim() !== ""
        ? "set (will send Discord alerts)"
        : "NOT set (local pop-ups only)"
    }`
  );
  console.log("\nStarting monitor...\n");

  // spawn monitor.js using the new .env
  const child = spawn("node", ["monitor.js"], {
    stdio: "inherit",
    env: { ...process.env }, // monitor.js will load the new .env via dotenv
  });

  child.on("exit", (code) => {
    console.log(`\nMonitor exited with code ${code}`);
  });
}

main().catch((err) => {
  console.error("Setup error:", err);
});



